const test=require('node:test');const assert=require('node:assert/strict');const {load,memoryStorage}=require('./helpers.cjs');
function subject({rows={},failure=null,rpc=async()=>({data:1,error:null})}={}){
 const disk=memoryStorage(),cache={},calls=[],session={user:{id:'alice'},access_token:'alice-token'};
 const client={auth:{getSession:async()=>({data:{session},error:null})},rpc:async(name,params)=>{calls.push({name,params});return rpc(name,params);},from(table){const query={select(){return this;},eq(){return this;},order(){return this;},async range(start,end){calls.push({table,start,end});return {data:(rows[table]??[]).slice(start,end+1),error:failure&&table===failure?{message:'read denied'}:null};}};return query;}};
 const mocks={'./authCrypto':{},'react-native-url-polyfill/auto':{},'react-native':{Platform:{OS:'ios'}},'@react-native-async-storage/async-storage':disk,'@supabase/supabase-js':{createClient:(url,key,options)=>{if(options.global)calls.push({authorization:options.global.headers.Authorization});return client;}},'expo-web-browser':{maybeCompleteAuthSession(){}},'expo-linking':{createURL:()=> 'caltracker://'}};
 return {api:load('src/services/supabase.ts',mocks,cache),storage:load('src/services/storage.ts',mocks,cache),client,calls,session};
}
const meal=id=>({id,name:'Real meal',date:'2026-09-29',timestamp:'2026-09-29T12:00:00Z',calories:100,protein:0,carbs:25,fats:0,mealType:'lunch'});
test('cloud pagination reads over 1500 meals with stable IDs and no 50-meal cap',async()=>{
 const rows={food_entries:Array.from({length:1502},(_,i)=>({id:'stable-'+i,name:'Meal',meal_type:'lunch',calories:100,protein:0,carbs:25,fats:0,date_str:'2026-09-29',created_at:'2026-09-29T12:00:00Z'}))};const {api,calls}=subject({rows});const cloud=await api.supabaseFetchAllUserData();assert.equal(cloud.snapshot.entries.length,1502);assert.equal(cloud.snapshot.entries.at(-1).id,'stable-1501');assert.equal(calls.filter(c=>c.table==='food_entries').length,4);assert.ok(calls.some(c=>c.authorization==='Bearer alice-token'));
});
test('failed table read rejects instead of returning an empty destructive snapshot',async()=>{const {api}=subject({failure:'weight_logs'});await assert.rejects(api.supabaseFetchAllUserData(),/read denied/);});
test('failed cloud write remains in the durable queue, with no success acknowledgement',async()=>{const {api,storage}=subject({rpc:async()=>({data:null,error:{message:'RLS denied'}})});await storage.setStorageScope('alice');await storage.saveFoodEntry(meal('local-id'));await assert.rejects(api.syncAccount(),/Cloud sync failed/);assert.equal((await storage.getPendingChanges()).length,1);assert.equal((await storage.getFoodEntries())[0].id,'local-id');});
test('sync sends every pending meal with its exact ID; deletion is a versioned tombstone',async()=>{const {api,storage,calls}=subject();await storage.setStorageScope('alice');await storage.saveFoodEntriesBatch(Array.from({length:75},(_,i)=>meal('meal-'+i)));await storage.deleteFoodEntry('meal-1');await api.syncAccount();const sent=calls.filter(c=>c.name==='apply_tracker_change');assert.equal(sent.length,75);assert.equal(sent.find(c=>c.params.p_key==='meal-1').params.p_deleted,true);assert.equal(sent.find(c=>c.params.p_key==='meal-74').params.p_payload.id,'meal-74');assert.equal((await storage.getPendingChanges()).length,0);});
test('conflict rejects and keeps the local edit',async()=>{const {api,storage}=subject({rpc:async()=>({data:null,error:{message:'sync conflict'}})});await storage.setStorageScope('alice');await storage.saveFoodEntry(meal('local-id'));await assert.rejects(api.syncAccount(),/another device/);assert.equal((await storage.getPendingChanges()).length,1);});
test('account mismatch cannot send another account’s queued records',async()=>{const {api,storage,calls}=subject();await storage.setStorageScope('bob');await storage.saveFoodEntry(meal('bob-meal'));await assert.rejects(api.syncAccount(),/account session changed/);assert.equal(calls.filter(c=>c.name==='apply_tracker_change').length,0);assert.equal((await storage.getPendingChanges()).length,1);});
test('guest data is never uploaded by a real signed-in session',async()=>{const {api,storage,calls}=subject();await storage.saveFoodEntry(meal('guest-meal'));await api.syncAccount();assert.equal(calls.filter(c=>c.name==='apply_tracker_change').length,0);assert.equal((await storage.getFoodEntries())[0].id,'guest-meal');});
test('invalid cloud acknowledgement cannot clear a queued edit',async()=>{const {api,storage}=subject({rpc:async()=>({data:null,error:null})});await storage.setStorageScope('alice');await storage.saveFoodEntry(meal('local-id'));await assert.rejects(api.syncAccount(),/acknowledgement was invalid/);assert.equal((await storage.getPendingChanges()).length,1);});
